version: '3.8'

services:
  web:
    image: abdulbasit5/myapp:latest
    ports:
      - "3000:3000"
    environment:
      - GREETING=Hello from Compose!
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASS=example
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:


